name: run-tests
on:
  workflow_call:
    inputs:
      node-matrix:
        description: "An array of node versions against which the tests should be run"
        required: false
        type: string
        default: "[{version: 'lts/*', artifact: 'lts'}]"
      java-matrix:
        description: "An array of java versions against which the tests should be run"
        required: false
        type: string
        default: "['11']"
      target-branch:
        description: "What branch should be checked out?"
        required: false
        type: string
        # If no target branch is specified, just use the one we'd use normally.
        default: ${{ github.sha }}

jobs:
  do-nothing:
    runs-on: ubuntu-latest
    steps:
      - run: echo DOING NOTHING FOR NOW
